# Generated by Django 4.1.1 on 2022-09-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cnpj",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
