# Generated by Django 4.1.1 on 2022-09-09 03:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("price", models.FloatField(blank=True, default=0, null=True)),
                ("sponsor", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="addresses.address",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="events", to="categories.category"
                    ),
                ),
            ],
        ),
    ]
