# Generated by Django 4.1.1 on 2022-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="site_url",
            field=models.TextField(null=True),
        ),
    ]
