# Generated by Django 4.1.1 on 2022-09-09 04:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("line_up", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineup",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1b9116b2-99dd-4791-9ea9-f88e06abf368"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
