# Generated by Django 4.1.1 on 2022-09-09 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("line_up", "0002_alter_lineup_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lineup",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
